# Generated by Django 4.1.7 on 2023-04-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flights',
            new_name='flight',
        ),
    ]
